service: serviceName

frameworkVersion: "3"

provider:
  name: aws
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  profile: default

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${sls:stage}-auth-user-pool
        MfaConfiguration: "OFF"
        Schema:
          - Name: email
            AttributeDataType: String
            Mutable: true
            Required: true
        UsernameAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${sls:stage}-auth-user-pool-client
        ExplicitAuthFlows:
          - ALLOW_REFRESH_TOKEN_AUTH
          - ALLOW_USER_PASSWORD_AUTH
        UserPoolId: !Ref CognitoUserPool

  Outputs:
    CognitoUserPoolId:
      Value:
        Ref: CognitoUserPool
      Export:
        Name: ${sls:stage}-CognitoUserPoolId

    CognitoUserPoolClientId:
      Value:
        Ref: CognitoUserPoolClient
      Export:
        Name: ${sls:stage}-CognitoUserPoolClientId
